---
options:
  deb_url:
    type: string
    default: "https://github.com/mozilla-services/heka/releases/download/v0.8.2/heka_0.8.2_amd64.deb"
    description: "Url to a debian package for heka"
  deb_md5:
    type: string
    default: dbd0b6151a7ce912a97440733b9a98b9
    description: "MD5 for result of 'deb_url'"
  docker_decoder:
    type: string
    default: ""
    description: "Decoder for DockerInput to use"
  juju_agent:
    type: boolean
    description: |
      Collect juju agent logs.
  extra_config:
    type: string
    description: |
      A url to a tarball or a git repository with additional toml
      files or sandbox code to run through templating and add to your
      heka