---
options:
  deb_url:
    type: string
    default: "https://github.com/mozilla-services/heka/releases/download/v0.9.2/heka_0.9.2_amd64.deb"
    description: "Url to a debian package for heka"
  deb_md5:
    type: string
    default: '8d08023d5fb31d0bb46d7943c5e1aca9'
    description: "MD5 for result of 'deb_url'"
  docker_decoder:
    type: string
    default: ""
    description: "Decoder for DockerInput to use"
  juju_agent:
    type: string
    default: 'none'
    description: |
      Collect juju agent logs.

      Defaults to `none` for no logs collected.

      - `all`: collect all logs for agents unit or machine
      - `machine`: only collect machine log
      - `self`: only collect log for unit agent for heka-sub
      - `service`: only collect logs for service which heka-sub relates
      - `unit`: only collect logs from unit agents (including heka-hub)

  extra_config:
    type: string
    description: |
      A url to a tarball or a git repository with additional toml
      files or sandbox code to run through templating and add to your
      heka